
[gcp_service_account]
type = "service_account"
project_id = "lp-app-469505"
private_key_id = "1e27603ff8a94589fcc9dd2cc93b7db5fac37cf3"

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCm5g/ERulKhUnL
J558mt72Zg335eVaAqXD9nCSJC6IJnyF8g2z0UlyIHm/eSiOUcbjM5elsGDA7XM2
KUbp6xQKb+BjceB171RG1Iwxl2DpsVU0IRy3y4C98fMoaBR/lDxj/jdOjVvT/Jj/
8BadCoopDN7Pfq5Kb1Bnpp4gbWJ3/gl/OgcvvT6x9E/hkmGx+sIjQE6sfPQc6I4P
bywtHZQnVPdDBti3PAOkIPK+CgBj3F61KOVlqj1piqiY+wRaCv9YJDZEeAKcb8LY
aHQY7mymupnjXGDTrMdzcWU7MbrFpR9JwZ3WKXqJF9Qzi2wXtl1CBrd7XyesYGK9
tkQaZcx3AgMBAAECggEAAdNW2ZRgXpKvvC37JUWd7t9CIT19qeOJEC0hDaDIw6rJ
8qr4R42gaTBRmEouISco6f3oF2zeFIWJTexHqPvQlesZ+LAvL/Yg5VKsKAyN6kfZ
5grD6KZxRYUSD249Pjyd2bf+hEJxkf/MyAL3vZWyAVUYyKizYLq+0PD2nkgHtSla
BUh1JVbUsSzLd0PPDfkoPG1ac4KrT1vz6UarhG0mIv+iw5MDp+frlJ36L9sKuqnh
FtlPweewJiP4Y4QWF8lKRJtHoAn5Q0LiJd5Qv9F5j7PJ0nJ/7YNM8FWUfqHs5YMZ
5wWiQKaNFdoeJJ5QiYDQS3WLWla19y1zqGtzavRHWQKBgQDoA+YQ2k2unSOb8LhG
EkyZ+XQZhvvpaF8PZg015RdfeFTHjHSbm3MucbPKaz2UiTuVKpw4qEZP2AtOidr8
r7vj4RX/Th0ltK26UxTV9Fn4bzw9k0G85Buc33bUJ7V0qy102hQiVD1rbAN671tn
rRXWAQCUCI+1CVXCbNzUNdvZtQKBgQC4JueE87sKkkPg8bAZ1WR1456DITP+2u4G
Ccotb4lXp/eQHY5Pg9SNzQZggX/fCMEELbFL6RMW+RogFkM/8YOHkmm/Np1tPDSv
/SA/IPTEq5j1E3iYAk2QdcugFOa59MdD7SMt1Boxv2L4xf0A4gbt158GgjLdntOp
PBj64zD4+wKBgQCvnpvb79JTNODKXeiuKZXQCvFljTZLk9Q4rK+dNv59JnFN5rQx
QPZrlmdX9drT/xiZrXo4rK8kKs1MMq8PC9o2AJ+M88y+SMgjvFWOKfqcQV6g4UEm
QKfiE4g3yKLiX9v1kkkhPxCKqmTr/hf7HxnjNjkA1IYqq5k9pPd2rhnu7QKBgC9P
Z2mDyIjVvPScgxaP+ShEWyPrMtWF32LTvwpfPlSzxWlT/oy1HLV1d+7xNi3RrOzq
5ELRVWMwiiK2NX7HCHibB+nlGRrIPez8xf0R9XBVeY10/CVpag30BWVSGViq50qv
MLuEY1pmhgHNs8s3RnpyS9u7NWA0fsJauzwxhBJjAoGAdHgsH02VQPIoEh4/wnNe
Ls7VBDrfbJCOoRGH3pmvgLACjExXW1sy1qLvvpwOJbKykGtfbq2RCr+AKXwu9cV8
Y59KUve3WBpeev9fB5sylk4zIK77e42nZT28WQPrP6cvhnVlW7IvYtRyw8GYl9s5
EebeLvS+LMt+Jjz0+Nz/DbM=
-----END PRIVATE KEY-----
"""

client_email = "lp-app-sa@lp-app-469505.iam.gserviceaccount.com"
client_id = "115922129818289923505"
token_uri = "https://oauth2.googleapis.com/token"

[gsheets]
spreadsheet_id = "1wezI95uZzl9I_ug7PJnLAVZlB0zC2JsWUI7AYr3rCOE"
worksheet = "Sheet1"
